---

- name: "Directory should be created with correct ownership and privileges"
  file:
    path: "/etc/graylog/server"
    owner: "graylog"
    group: "graylog"
    mode: 0750

- name: "Graylog server should be configured"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server defaults should be configured"
  template:
    src: "graylog.server.default.j2"
    dest: "{{ graylog_server_defaults_file_path }}"
    owner: "graylog"
    group: "graylog"
    mode: 0644
  notify: "restart graylog-server"

- name: "Graylog server should start after reboot"
  file:
    path: "/etc/init/graylog-server.override"
    state: "absent"

- meta: "flush_handlers"

- debug:
    var: graylog_http_bind_address
    
- name: "Wait for Graylog server to startup"
  uri:
    url: "http://{{ graylog_http_bind_address }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: graylog_not_testing
